image: maven:eclipse-temurin

stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn clean test
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

package:
  stage: package
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/IDATT2003-ChaosGame-0.1-SNAPSHOT.jar

